export const productsData = [
  {
    id: 'metal-nfc-card',
    name_en: "Metal Magnetic NFC Card",
    name_ar: "بطاقة تعارف ممغنطة معدني - نضع تصميمك",
    description_en: "A full-metal NFC business card built for people who want their first impression to last. One tap against any modern iPhone or Android shares your contact details, social profiles, and website instantly — no app required, no paper card to run out of. Your name or logo is precision-engraved into the metal surface, giving it the weight and finish that suits executives and business owners who meet clients face to face. No battery, no charging, works for years.",
    description_ar: "بطاقة أعمال ذكية NFC مصنوعة من معدن فاخر بالكامل، مصممة لمن يريد انطباعاً أولاً لا يُنسى في الاجتماعات وفعاليات الأعمال. بلمسة واحدة من الهاتف، تُشارك بياناتك الكاملة: رقم الجوال، البريد الإلكتروني، حساباتك على وسائل التواصل، وموقعك الإلكتروني، دون الحاجة لتطبيق أو طباعة بطاقات ورقية تنتهي صلاحيتها. نقش تصميمك أو شعار شركتك على سطح المعدن بدقة عالية، ويناسب المدراء التنفيذيين وأصحاب الأعمال. متوافقة مع جميع هواتف آيفون وأندرويد الحديثة، ولا تحتاج شحن أو بطارية.",
    price: 130,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/12/Frame_44_1b99c720-5d9b-492e-b5fa-ea176d50a2ad-450x450.webp",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Metal material', 'Magnetic', 'Custom design', 'Premium finish'],
    features_ar: ['مادة معدنية', 'مغناطيسي', 'تصميم مخصص', 'لمسة نهائية فاخرة']
  },
  {
    id: 'wooden-nfc-card',
    name_en: "Wooden NFC Business Card",
    name_ar: "بطاقة تعارف إلكتروني للمشاركة السريعة NFC - خشبي (تصميم مخصص)",
    description_en: "A genuine wooden NFC business card for people who want something warmer and more sustainable than plastic. Your design or logo is laser-engraved straight into the wood grain, so no two cards look quite the same. Tap it against any phone and the person you're meeting instantly gets your number, email, and social profiles — no app needed. A natural fit for creative founders, cafés, and brands built around an eco-friendly identity. Lightweight, durable, and needs no battery.",
    description_ar: "بطاقة تعارف NFC مصنوعة من خشب طبيعي بالكامل، لكل من يبحث عن بديل أنيق ومستدام عن البطاقات البلاستيكية والورقية التقليدية. يُحفر تصميمك أو شعارك بالليزر مباشرة على سطح الخشب بدقة عالية، فتحصل على بطاقة فريدة لا تتكرر لدى أحد غيرك. بلمسة واحدة على الهاتف، يستقبل من تقابله رقمك وبريدك الإلكتروني وحساباتك على مواقع التواصل الاجتماعي دون تحميل أي تطبيق. خيار مثالي لأصحاب المشاريع الإبداعية والمقاهي والعلامات التجارية ذات الهوية الطبيعية الصديقة للبيئة.",
    price: 100,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/10/%D8%B9%D9%85%D8%A7%D8%AF-%D8%B1%D8%AF%D9%85%D8%A7%D9%86-3-450x450.png",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Natural wood', 'Laser engraving', 'Eco-friendly', 'Custom design'],
    features_ar: ['خشب طبيعي', 'حفر بالليزر', 'صديق للبيئة', 'تصميم مخصص']
  },
  {
    id: 'magnetic-nfc-card',
    name_en: "Magnetic NFC Business Card",
    name_ar: "بطاقة تعارف ممغنطة NFC (تصميم مخصص)",
    description_en: "A premium plastic NFC card with a magnetic back that makes it easier to carry and store than a standard card. It's the practical pick for anyone who wants a smart business card without the premium price tag — one tap shares your number, email, and social profiles (Instagram, Snapchat, WhatsApp) directly to the other person's phone. Customize it with your own colors and logo — a good fit for sales teams who need several cards at once.",
    description_ar: "بطاقة أعمال NFC بلاستيكية فاخرة بميزة مغناطيسية تجعل حفظها في المحفظة أسهل من أي بطاقة تقليدية. صُممت لتكون الخيار العملي لمن يحتاج بطاقة تعارف ذكية بسعر مناسب دون التنازل عن الجودة: بلمسة واحدة من الهاتف تنتقل بياناتك كاملة، أرقام التواصل، البريد الإلكتروني، وحساباتك على إنستقرام وسناب شات وواتساب، مباشرة لهاتف من تقابله. صممها بألوانك وشعارك الخاص، وتناسب فرق المبيعات والموظفين الذين يحتاجون بطاقات متعددة بأسعار معقولة.",
    price: 50,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/10/6-450x450.png",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Magnetic back', 'Custom design', 'Premium plastic', 'Quick sharing'],
    features_ar: ['ظهر مغناطيسي', 'تصميم مخصص', 'بلاستيك فاخر', 'مشاركة سريعة']
  },
  {
    id: 'google-review-card',
    name_en: "Google Review NFC Card",
    name_ar: "بطاقة قيمنا على جوجل - NFC",
    description_en: "An NFC card built specifically to collect Google reviews on the spot, before a customer leaves and forgets. Instead of asking someone to remember to review you later, tap the card against their phone and your Google review page opens instantly, ready to write and post in seconds. One of the fastest ways to raise your review count and improve how your business ranks on Google Search and Maps. A natural fit for shops, clinics, restaurants, and salons.",
    description_ar: "بطاقة NFC مخصصة لمساعدتك على جمع تقييمات جوجل بسرعة من عملائك داخل متجرك أو عيادتك أو مطعمك. بدلاً من طلب التقييم شفهياً وانتظار أن يتذكر العميل كتابته لاحقاً، تُقرّب البطاقة من هاتفه فيُفتح رابط تقييم جوجل مباشرة، جاهزاً للكتابة والنشر خلال ثوانٍ. الحل الأسرع لرفع عدد تقييماتك وتحسين ترتيب نشاطك التجاري في نتائج بحث جوجل والخرائط. مثالية للمحلات والعيادات والمطاعم والصالونات التي تعتمد على السمعة الرقمية لجذب عملاء جدد.",
    price: 35,
    original_price: 60,
    discount_percentage: 42,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/12/Google-NFC-Instagam-Facebook-WhatsApp-Youtube-Snapchat-Android-iPhone-450x450.webp",
    category: "business_cards",
    is_customizable: false,
    features_en: ['Direct to Google', 'Instant reviews', 'Professional look', 'Easy to use'],
    features_ar: ['مباشرة لجوجل', 'تقييمات فورية', 'مظهر احترافي', 'سهل الاستخدام']
  },
  {
    id: 'review-keychain',
    name_en: "NFC Review Keychain",
    name_ar: "تعليقة مفاتيح NFC لزيادة مراجعات",
    description_en: "An NFC keychain that makes asking for a Google review possible anywhere, not just at a checkout counter. Clip it to your keys or leave it in the car, and whenever a happy customer is in front of you, tap it against their phone to open your review page instantly. Its small size makes it practical for people who work on the move — sales reps, home service providers, delivery drivers. Needs no charging or maintenance.",
    description_ar: "تعليقة مفاتيح بتقنية NFC مصممة لتسهّل عليك طلب تقييم جوجل من عملائك في أي مكان، حتى خارج المتجر. علّقها بمفاتيحك أو في سيارتك، وعند كل عميل راضٍ عن خدمتك، قرّبها من هاتفه ليفتح رابط التقييم مباشرة دون كتابة أو بحث. حجمها الصغير يجعلها عملية لأصحاب الأعمال المتنقلين مثل مندوبي المبيعات وأصحاب الخدمات المنزلية وسائقي التوصيل. متوفرة بعدة ألوان، متينة للاستخدام اليومي، ولا تحتاج شحن أو صيانة.",
    price: 45,
    original_price: 75,
    discount_percentage: 40,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/12/NFC-Epoxy-Keychain-NFC-Google-450x450.webp",
    category: "keychains",
    is_customizable: true,
    features_en: ['Compact design', 'Durable', 'Multiple colors', 'Review collection'],
    features_ar: ['تصميم مدمج', 'متين', 'ألوان متعددة', 'جمع التقييمات']
  },
  {
    id: 'social-keychain',
    name_en: "Social Media NFC Keychain",
    name_ar: "تعليقة مفاتيح وسائل التواصل (NFC)",
    description_en: "An NFC keychain built to share every social profile you have with one tap — no typing a username, no scanning a QR code. Link it to your Instagram, Snapchat, TikTok, and WhatsApp, and tapping it against any phone opens them all at once. A solid pick for influencers and small business owners who want a fast way to pick up new followers at events and in-person meetings. Compact and easy to carry on your everyday keychain.",
    description_ar: "تعليقة مفاتيح NFC لمشاركة جميع حساباتك على وسائل التواصل الاجتماعي بلمسة واحدة، دون الحاجة لطلب اليوزر أو مسح رمز QR. اربطها بحساباتك على إنستقرام، سناب شات، تيك توك، وواتساب، وعند تقريبها من أي هاتف يفتح كل شيء دفعة واحدة. خيار مثالي للمؤثرين وأصحاب الأعمال الصغيرة الذين يريدون طريقة سريعة لكسب متابعين جدد في اللقاءات والفعاليات. تصميم أنيق وعملي يناسب حلقة المفاتيح اليومية.",
    price: 35,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/12/Instagram-NFC-Epoxy-Tag-NFC-Key-Card-13-56MHz-URL-Link-450x450.webp",
    category: "keychains",
    is_customizable: true,
    features_en: ['All platforms', 'Instant connect', 'Stylish design', 'Multiple options'],
    features_ar: ['جميع المنصات', 'اتصال فوري', 'تصميم أنيق', 'خيارات متعددة']
  },
  {
    id: 'premium-table-stand',
    name_en: "Premium Google Review Table Stand - NFC",
    name_ar: "ستاند طاولة فخامة لطلب التقييم على جوجل - NFC",
    description_en: "A premium acrylic table stand with built-in NFC, made to collect Google reviews from customers right where they sit or pay. Place it on a table or next to the register, and a single tap opens your Google review page, ready to write. Its clean acrylic design fits naturally into a shop, café, or clinic without taking up counter space. Built for businesses with daily walk-in traffic that want more reviews with the least friction for the customer.",
    description_ar: "ستاند طاولة فاخر بتقنية NFC مخصص لجمع تقييمات جوجل من عملائك داخل محلك أو مطعمك أو عيادتك. ضعه على الطاولة أو بجانب الكاشير، وبمجرد أن يقرّب العميل هاتفه منه يفتح رابط تقييم جوجل جاهزاً للكتابة مباشرة. مصنوع من أكريليك فاخر بتصميم أنيق يليق بواجهة عملك ولا يشغل مساحة كبيرة. الحل الأمثل للأنشطة التي تستقبل عملاء يومياً وتريد رفع عدد تقييماتها بأقل جهد ممكن، من مطاعم وكافيهات إلى عيادات وصالونات تجميل.",
    price: 120,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/12/unnamed-file-12-450x450.webp",
    category: "stands",
    is_customizable: false,
    features_en: ['Premium acrylic', 'Desk stand', 'Professional look', 'Easy placement'],
    features_ar: ['أكريليك فاخر', 'حامل مكتب', 'مظهر احترافي', 'وضع سهل']
  },
  {
    id: 'quick-share-stand',
    name_en: "Quick Share Table Stand",
    name_ar: "ستاند طاولة للمشاركة السريعة (معلومات التواصل الاجتماعي ، منيو ، الموقع ..)",
    description_en: "A multi-purpose NFC table stand for sharing whatever you need with a single tap: your menu, website, social profiles, or an order form. When a customer taps their phone against it, whatever link you've set opens instantly. Fully customizable, so it can serve a different purpose depending on your business — a flexible option for restaurants and cafés looking to replace paper menus or QR codes with something faster and more professional.",
    description_ar: "ستاند طاولة متعدد الاستخدامات بتقنية NFC، لمشاركة أي معلومة تريدها بلمسة واحدة: منيو المطعم، رابط الموقع الإلكتروني، حسابات التواصل الاجتماعي، أو نموذج طلب. عند تقريب العميل هاتفه من الستاند، يفتح مباشرة الرابط الذي تحدده أنت. يمكن تخصيصه ليعرض معلومات مختلفة حسب طبيعة نشاطك، ما يجعله خياراً مرناً للمطاعم والمقاهي التي تريد استبدال قوائم الطعام الورقية أو رموز QR بتجربة أسرع وأكثر احترافية.",
    price: 129,
    original_price: 159,
    discount_percentage: 19,
    image_url: "https://beta.rawajcard.com/wp-content/uploads/2024/10/InstagramStandwhite_1800x1800-450x450.webp",
    category: "stands",
    is_customizable: true,
    features_en: ['Multi-purpose', 'Acrylic stand', 'Custom info', 'Restaurant ready'],
    features_ar: ['متعدد الأغراض', 'حامل أكريليك', 'معلومات مخصصة', 'جاهز للمطاعم']
  }
];

export const productCategories = [
  { value: 'all', label_en: 'All Products', label_ar: 'جميع المنتجات', icon: '🛍️' },
  { value: 'business_cards', label_en: 'Business Cards', label_ar: 'بطاقات الأعمال', icon: '📱' },
  { value: 'keychains', label_en: 'Keychains', label_ar: 'تعليقات المفاتيح', icon: '🔑' },
  { value: 'stands', label_en: 'Table Stands', label_ar: 'ستاندات الطاولة', icon: '📊' }
];