-- ══════════════════════════════════════════════════════════════════
-- Run this entire file in: Supabase Dashboard → SQL Editor → Run
-- ══════════════════════════════════════════════════════════════════
--
-- 1) Adds a `video_url` column so admins can attach a product video
--    (uploaded file or an external YouTube/Vimeo link) from the admin panel.
-- 2) Replaces the short, generic seed descriptions with long-form,
--    SEO-optimised bilingual copy, expanded features, and keyword
--    lists for each of the existing published products.
--
-- Uses dollar-quoted strings ($en$ / $ar$ / $kw$) so the copy below
-- (which includes apostrophes) doesn't need manual escaping.
-- Safe to run multiple times.

alter table public.products
  add column if not exists video_url text;

-- ── Metal Magnetic NFC Card ─────────────────────────────────────────
update public.products set
  description = $en$Make every introduction count with Rawajcard's all-metal NFC business card — a premium, tap-to-share card built for executives, business owners, and sales professionals who meet clients face to face. A single tap against any NFC-enabled iPhone (iOS 11+) or Android phone instantly shares your full contact card: phone number, email, website, and every social media profile you want to include — no app to download, no typing, and no paper card that runs out. If the other person's phone doesn't support NFC, the built-in QR code on the card works as an instant backup, so you never miss a connection. Your name, logo, or company branding is precision-engraved into the solid metal surface for a finish that feels as premium as the brand it represents. The card is fully reprogrammable, so you can update your linked information any time your details change — no need to reorder. With no battery and nothing to charge, it's built to last for years of daily use. Available in a magnetic-back variant for easier storage in your wallet or cardholder. A popular choice for CEOs, real estate agents, consultants, and luxury service providers across Saudi Arabia who want their first impression to match the level of their work.$en$,
  description_ar = $ar$اجعل كل تعارف يترك انطباعاً يليق بك مع بطاقة رواج كارد المعدنية بتقنية NFC — بطاقة أعمال ذكية فاخرة مصممة للمدراء التنفيذيين وأصحاب الأعمال ورجال المبيعات الذين يقابلون عملاءهم وجهاً لوجه. بلمسة واحدة من أي هاتف آيفون يدعم NFC (من إصدار iOS 11 فأعلى) أو هاتف أندرويد حديث، تنتقل بطاقتك الرقمية الكاملة فوراً: رقم الجوال، البريد الإلكتروني، الموقع الإلكتروني، وجميع حساباتك على وسائل التواصل الاجتماعي — دون تطبيق، ودون كتابة، ودون بطاقات ورقية تنتهي كمياتها. وإذا لم يدعم هاتف الطرف الآخر تقنية NFC، يعمل رمز QR المدمج في البطاقة كبديل فوري لضمان عدم فوات أي فرصة تواصل. يُنقش اسمك أو شعار شركتك بدقة عالية على سطح معدني بالكامل، لتحصل على بطاقة بمستوى الفخامة الذي يليق بعملك. البطاقة قابلة لإعادة البرمجة في أي وقت عند تغيّر بياناتك، دون الحاجة لطلب بطاقة جديدة. لا تحتاج بطارية ولا شحناً، وتدوم لسنوات من الاستخدام اليومي. متوفرة بخيار الظهر المغناطيسي لتخزين أسهل داخل محفظتك. الخيار المفضل للمدراء التنفيذيين والوسطاء العقاريين والاستشاريين ومقدمي الخدمات الفاخرة في السعودية.$ar$,
  seo_keywords = $kw$metal NFC business card, engraved metal business card, NFC card Saudi Arabia, custom NFC business card, tap to share contact card, luxury NFC card for executives, بطاقة تعارف معدنية NFC, بطاقة اعمال ذكية بالسعودية, بطاقة تعريف معدنية فاخرة, افضل بطاقة NFC للمدراء التنفيذيين$kw$,
  features_en = '["Solid metal construction","Laser-engraved custom design","Tap or QR code sharing","Reprogrammable anytime","Works with iPhone & Android","No app or battery required","Optional magnetic back"]',
  features_ar = '["بناء معدني بالكامل","نقش ليزر لتصميمك الخاص","مشاركة باللمس أو مسح QR","إعادة برمجة في أي وقت","يعمل مع آيفون وأندرويد","بدون تطبيق أو بطارية","خيار الظهر المغناطيسي"]'
where slug = 'metal-nfc-card';

-- ── Wooden NFC Business Card ────────────────────────────────────────
update public.products set
  description = $en$Give your introduction a warmer, more memorable feel with Rawajcard's genuine wooden NFC business card. Cut from real wood and laser-engraved with your name, logo, or design, every card carries a unique grain pattern, so no two cards are exactly alike. Tap it against any modern NFC-enabled phone and your contact details, social media accounts, and website open instantly on the other person's screen — no app required. A built-in QR code gives you a reliable backup for phones without NFC support. Lightweight, naturally durable, and completely free of plastic, it's the card of choice for creative founders, boutique studios, cafés, and sustainability-focused brands that want their branding to reflect their values as much as their message. The wood surface takes engraving beautifully, making logos and monograms stand out with a texture no printed card can match. Like every Rawajcard NFC card, it's reprogrammable any time your information changes, needs no battery or charging, and keeps working for years. If you want a business card that starts a conversation before you even say a word, this is it.$en$,
  description_ar = $ar$امنح تعارفك لمسة أكثر دفئاً وتميزاً مع بطاقة رواج كارد الخشبية بتقنية NFC. مصنوعة من خشب طبيعي بالكامل ومنقوشة بالليزر باسمك أو شعارك أو تصميمك، بحيث تحمل كل بطاقة نقشة خشبية فريدة لا تتكرر في بطاقة أخرى. بمجرد تقريبها من أي هاتف حديث يدعم NFC، تنتقل بياناتك وحساباتك على وسائل التواصل وموقعك الإلكتروني فوراً إلى شاشة الطرف الآخر، دون الحاجة لأي تطبيق. ويوفر رمز QR المدمج بديلاً موثوقاً للهواتف التي لا تدعم NFC. خفيفة الوزن ومتينة بطبيعتها وخالية تماماً من البلاستيك، فهي الخيار المفضل لأصحاب المشاريع الإبداعية والاستوديوهات المتخصصة والمقاهي والعلامات التجارية المهتمة بالاستدامة، والتي تريد أن يعكس تصميم بطاقتها قيمها بقدر ما يعكس رسالتها. يتقبل سطح الخشب النقش بجمالية عالية، فيبرز الشعار أو الحروف الأولى بملمس لا تستطيع أي بطاقة مطبوعة تقليده. وكبقية بطاقات رواج كارد، هي قابلة لإعادة البرمجة في أي وقت، ولا تحتاج بطارية أو شحناً، وتستمر لسنوات طويلة.$ar$,
  seo_keywords = $kw$wooden NFC business card, eco-friendly business card Saudi Arabia, laser engraved wood card, sustainable NFC card, custom wooden card, natural wood tap card, بطاقة تعارف خشبية NFC, بطاقة اعمال صديقة للبيئة, بطاقة خشب مخصصة بالسعودية$kw$,
  features_en = '["100% natural wood","Unique laser-engraved grain","Tap or QR code sharing","Eco-friendly, plastic-free","Reprogrammable anytime","Lightweight & durable","Works with iPhone & Android"]',
  features_ar = '["خشب طبيعي 100%","نقش ليزر بنقشة فريدة","مشاركة باللمس أو QR","صديقة للبيئة وخالية من البلاستيك","إعادة برمجة في أي وقت","خفيفة ومتينة"]'
where slug = 'wooden-nfc-card';

-- ── Magnetic NFC Business Card (plastic) ─────────────────────────────
update public.products set
  description = $en$Not every business needs a metal or wood card to make an impression — sometimes the smartest choice is a reliable, affordable NFC card that does the job perfectly. Rawajcard's magnetic plastic NFC card gives you the same one-tap sharing power as our premium cards, at a price that makes sense for sales teams, employees, and growing businesses that need several cards at once. The magnetic back holds the card securely in a wallet, phone case, or card holder, so it's always within reach when you need it. One tap on any NFC-enabled iPhone or Android instantly shares your number, email, and social profiles like Instagram, Snapchat, and WhatsApp — with the built-in QR code as a backup for older phones. Fully customizable with your own colors, logo, and layout, it looks as professional as it is practical. Like every Rawajcard NFC product, it's reprogrammable whenever your details change, so a growing team can update every card in minutes without reordering. If you need multiple cards without multiplying your budget, this is the practical choice.$en$,
  description_ar = $ar$لا تحتاج كل الأعمال إلى بطاقة معدنية أو خشبية لترك انطباع جيد — أحياناً يكون الخيار الأذكى بطاقة NFC عملية وبسعر مناسب تؤدي المهمة بكفاءة. توفر بطاقة رواج كارد البلاستيكية الممغنطة نفس قوة المشاركة بلمسة واحدة التي تقدمها بطاقاتنا الفاخرة، بسعر يناسب فرق المبيعات والموظفين والأعمال النامية التي تحتاج عدة بطاقات دفعة واحدة. يثبّت الظهر المغناطيسي البطاقة بأمان داخل المحفظة أو جراب الهاتف أو حافظة البطاقات، لتكون دائماً في متناول يدك عند الحاجة. بلمسة واحدة من أي هاتف آيفون أو أندرويد يدعم NFC، تنتقل بياناتك ورقمك وبريدك الإلكتروني وحساباتك على إنستقرام وسناب شات وواتساب فوراً، مع رمز QR مدمج كبديل للهواتف الأقدم. قابلة للتخصيص الكامل بألوانك وشعارك وتصميمك الخاص، لتبدو احترافية بقدر ما هي عملية. وكبقية منتجات رواج كارد NFC، يمكن إعادة برمجتها في أي وقت تتغير فيه بياناتك، ما يتيح لفريق متنامٍ تحديث جميع البطاقات خلال دقائق دون إعادة طلب. إذا كنت بحاجة لعدة بطاقات دون مضاعفة ميزانيتك، فهذا هو الخيار العملي.$ar$,
  seo_keywords = $kw$magnetic NFC business card, affordable NFC card Saudi Arabia, plastic NFC card for teams, cheap NFC business card, bulk NFC cards for employees, بطاقة تعارف ممغنطة بلاستيك, بطاقة NFC رخيصة السعودية, بطاقة اعمال للموظفين$kw$,
  features_en = '["Magnetic back for easy carry","Affordable & durable plastic","Tap or QR code sharing","Fully customizable colors & logo","Reprogrammable anytime","Great for teams & multiple staff"]',
  features_ar = '["ظهر مغناطيسي لحمل سهل","بلاستيك متين وبسعر مناسب","مشاركة باللمس أو QR","تخصيص كامل للألوان والشعار","إعادة برمجة في أي وقت","مثالية للفرق والموظفين"]'
where slug = 'magnetic-nfc-card';

-- ── Google Review NFC Card ──────────────────────────────────────────
update public.products set
  description = $en$Getting customers to leave a Google review is usually the hardest part — Rawajcard's Google Review NFC card removes almost every excuse. Instead of asking a customer to remember your business name later, hand them the card or place it at the counter: one tap on any NFC-enabled phone opens your Google review page immediately, cursor ready, review pending. There's no app to search for, no typing your business name, and no waiting on a text message link that might get ignored. For phones without NFC, the built-in QR code opens the same review page with a second scan. More reviews collected in the moment means a stronger star rating and better visibility in Google Search and Google Maps — both of which directly influence how many new customers find you before they find your competitors. It's a natural fit for restaurants, clinics, salons, retail shops, and any business that relies on local search and word of mouth. Set it up once, and every satisfied customer becomes a two-second opportunity to grow your online reputation.$en$,
  description_ar = $ar$الحصول على تقييم من العميل في جوجل عادة هو الجزء الأصعب — بطاقة رواج كارد لتقييم جوجل NFC تزيل معظم الأعذار. بدلاً من أن تطلب من العميل أن يتذكر اسم نشاطك التجاري لاحقاً، قدّم له البطاقة أو ضعها عند الكاشير: بلمسة واحدة من أي هاتف يدعم NFC يفتح رابط تقييم جوجل مباشرة، جاهزاً للكتابة فوراً. لا حاجة للبحث عن تطبيق، ولا كتابة اسم نشاطك، ولا انتظار رسالة نصية قد يتجاهلها العميل. أما الهواتف التي لا تدعم NFC، فيفتح رمز QR المدمج نفس صفحة التقييم بمسحة واحدة. جمع تقييمات أكثر في اللحظة المناسبة يعني تقييماً أعلى وظهوراً أفضل في بحث جوجل وخرائط جوجل — وكلاهما يؤثر مباشرة في عدد العملاء الجدد الذين يجدونك قبل أن يجدوا منافسيك. خيار مثالي للمطاعم والعيادات وصالونات التجميل والمحلات وأي نشاط يعتمد على البحث المحلي وكلام الأفواه. جهّزها مرة واحدة، وحوّل كل عميل راضٍ إلى فرصة تستغرق ثانيتين لتنمية سمعتك الرقمية.$ar$,
  seo_keywords = $kw$Google review NFC card, tap to review card Saudi Arabia, boost Google reviews fast, Google review tap tag, NFC card for local SEO, increase business reviews, بطاقة تقييم جوجل NFC, زيادة تقييمات جوجل, بطاقة تقييمات للمحلات السعودية$kw$,
  features_en = '["Direct one-tap to Google review page","QR code backup for any phone","Boosts star rating fast","Improves Google Search & Maps ranking","No app needed for customers","Great for shops, clinics & restaurants"]',
  features_ar = '["فتح مباشر لصفحة تقييم جوجل بلمسة","رمز QR بديل لكل الهواتف","رفع التقييم بسرعة","تحسين الظهور في بحث وخرائط جوجل","لا حاجة لتطبيق من العميل","مثالية للمحلات والعيادات والمطاعم"]'
where slug = 'google-review-card';

-- ── NFC Review Keychain ──────────────────────────────────────────────
update public.products set
  description = $en$Not every great review moment happens inside your shop — Rawajcard's NFC review keychain lets you ask for one anywhere. Clip it to your keys, hang it in your car, or carry it in your pocket, and the moment a customer tells you how happy they are, tap the keychain against their phone to open your Google review page on the spot. There's no waiting for them to get home and forget, and no follow-up message that goes unanswered. Its compact size makes it especially practical for people who work on the move — sales reps, home service technicians, delivery drivers, real estate agents, and freelancers meeting clients outside a fixed location. Like every Rawajcard NFC product, it needs no app for the customer, no battery, and no charging, and it's built to handle daily use on a busy keyring. Available in multiple colors so it fits your personal or brand style. If your best reviews happen outside your storefront, this keychain makes sure you never miss the chance to collect them.$en$,
  description_ar = $ar$لا تحدث كل لحظة تقييم رائعة داخل متجرك — تعليقة مفاتيح رواج كارد بتقنية NFC تتيح لك طلب التقييم في أي مكان. علّقها بمفاتيحك، أو اتركها في سيارتك، أو احملها في جيبك، وبمجرد أن يخبرك عميل بمدى رضاه، قرّب التعليقة من هاتفه لفتح صفحة تقييم جوجل فوراً. لا انتظار حتى يعود لمنزله وينسى، ولا رسالة متابعة قد لا يرد عليها. حجمها المدمج يجعلها عملية بشكل خاص لأصحاب الأعمال المتنقلين — مندوبي المبيعات، فنيي الخدمات المنزلية، سائقي التوصيل، الوسطاء العقاريين، والمستقلين الذين يقابلون عملاءهم خارج مكان ثابت. وكبقية منتجات رواج كارد NFC، لا تحتاج تطبيقاً من العميل، ولا بطارية، ولا شحناً، ومصممة لتحمل الاستخدام اليومي على حلقة مفاتيح مزدحمة. متوفرة بعدة ألوان لتناسب أسلوبك الشخصي أو هوية علامتك. إذا كانت أفضل تقييماتك تحدث خارج متجرك، فهذه التعليقة تضمن ألا تفوّت فرصة جمعها.$ar$,
  seo_keywords = $kw$NFC review keychain, Google review keychain Saudi Arabia, portable review tag, tap to review keychain, NFC keychain for business, review collector for mobile teams, تعليقة مفاتيح تقييم جوجل, ميدالية NFC للتقييمات, تعليقة مفاتيح للمهن المتنقلة$kw$,
  features_en = '["Portable — clips to any keyring","Instant tap-to-review anywhere","No app or battery needed","Durable for daily carry","Multiple color options","Ideal for mobile professionals"]',
  features_ar = '["محمولة — تُعلّق بأي حلقة مفاتيح","تقييم فوري بلمسة في أي مكان","بدون تطبيق أو بطارية","متينة للاستخدام اليومي","ألوان متعددة","مثالية للمهن المتنقلة"]'
where slug = 'review-keychain';

-- ── Social Media NFC Keychain ────────────────────────────────────────
update public.products set
  description = $en$Stop repeating your Instagram handle and spelling out your username at every event — Rawajcard's social media NFC keychain shares all of your profiles with a single tap. Link it to your Instagram, Snapchat, TikTok, and WhatsApp, and when you tap it against someone's phone, every account you've linked opens at once, ready to follow. No QR code to scan, no typing, and no chance of a misspelled username costing you a follower. It's a natural fit for influencers, content creators, and small business owners who meet new people at events, pop-ups, and in-person meetings and want a faster way to turn a conversation into a follow. Small enough to live on your everyday keychain, it's always with you when the right moment comes up. As with every Rawajcard NFC product, there's no app required for the other person, no battery, and no charging — just tap and connect. If your following grows one handshake at a time, this keychain makes each one count.$en$,
  description_ar = $ar$توقف عن تكرار يوزر إنستقرام أو تهجئة اسم حسابك في كل فعالية — تعليقة مفاتيح رواج كارد لوسائل التواصل الاجتماعي تشارك جميع حساباتك بلمسة واحدة. اربطها بحساباتك على إنستقرام، سناب شات، تيك توك، وواتساب، وعند تقريبها من هاتف أي شخص، تفتح كل الحسابات التي ربطتها دفعة واحدة وجاهزة للمتابعة. لا حاجة لمسح رمز QR، ولا كتابة، ولا احتمال خطأ إملائي في اسم الحساب يكلفك متابعاً. خيار مثالي للمؤثرين وصناع المحتوى وأصحاب الأعمال الصغيرة الذين يقابلون أشخاصاً جدداً في الفعاليات والمعارض واللقاءات المباشرة، ويريدون طريقة أسرع لتحويل محادثة إلى متابعة. صغيرة بما يكفي لتعيش على حلقة مفاتيحك اليومية، فتكون دائماً معك عندما تأتي اللحظة المناسبة. وكبقية منتجات رواج كارد NFC، لا يحتاج الطرف الآخر لأي تطبيق، ولا بطارية، ولا شحن — فقط قرّب وتواصل. إذا كانت متابعتك تنمو بمصافحة واحدة في كل مرة، فهذه التعليقة تجعل كل مصافحة تُحتسب.$ar$,
  seo_keywords = $kw$social media NFC keychain, Instagram NFC tag Saudi Arabia, NFC keychain for influencers, tap to follow keychain, NFC social profile card, event networking NFC tag, تعليقة مفاتيح مواقع التواصل, ميدالية NFC انستقرام, تعليقة NFC للمؤثرين$kw$,
  features_en = '["Shares Instagram, Snapchat, TikTok & WhatsApp","One tap opens all your profiles","No QR code or typing needed","Compact everyday keychain design","No app or battery required","Great for influencers & event networking"]',
  features_ar = '["مشاركة إنستقرام وسناب شات وتيك توك وواتساب","لمسة واحدة تفتح جميع حساباتك","بدون رمز QR أو كتابة","تصميم مدمج لحلقة المفاتيح اليومية","بدون تطبيق أو بطارية","مثالية للمؤثرين والتواصل بالفعاليات"]'
where slug = 'social-keychain';

-- ── Premium Google Review Table Stand ────────────────────────────────
update public.products set
  description = $en$Turn every table, counter, or till point into a review-collecting moment with Rawajcard's premium acrylic table stand. Built with an NFC chip inside a clean, professional acrylic frame, it sits naturally on a table, counter, or next to the register without looking like signage. The moment a customer is ready to pay or finishing their visit, a single tap of their phone opens your Google review page instantly — no searching, no typing, just a review ready to post. Its elegant, minimal design fits the look of restaurants, cafés, clinics, salons, and retail stores that want their in-store branding to feel premium, not promotional. Because it stays in one place, it works passively all day, every day, quietly turning satisfied customers into public reviews without needing staff to ask each time. Combined with a QR code for phones without NFC, it captures reviews from virtually every customer who's willing to leave one. For businesses that depend on daily foot traffic and local reputation, it's one of the simplest ways to keep new reviews coming in with the least effort.$en$,
  description_ar = $ar$حوّل كل طاولة أو كاشير في نشاطك التجاري إلى نقطة لجمع التقييمات مع ستاند رواج كارد الأكريليك الفاخر. مصمم بشريحة NFC داخل إطار أكريليك أنيق واحترافي، يتناسب مع الطاولة أو الكاشير دون أن يبدو كلوحة إعلانية. بمجرد أن يكون العميل جاهزاً للدفع أو ينهي زيارته، تفتح لمسة واحدة من هاتفه صفحة تقييم جوجل فوراً — دون بحث أو كتابة، والتقييم جاهز للنشر. تصميمه الأنيق والبسيط يناسب مظهر المطاعم والمقاهي والعيادات وصالونات التجميل والمحلات التي تريد أن تعكس هويتها الداخلية طابعاً فاخراً لا ترويجياً. ولأنه يبقى في مكانه، يعمل بشكل مستمر طوال اليوم، كل يوم، محوّلاً العملاء الراضين إلى تقييمات علنية دون الحاجة لأن يطلب الموظفون ذلك في كل مرة. وبفضل رمز QR المدمج للهواتف التي لا تدعم NFC، يجمع تقييمات من كل عميل تقريباً يرغب بترك تقييم. لأصحاب الأعمال الذين يعتمدون على حركة يومية وسمعة محلية قوية، هذا الستاند من أبسط الطرق لضمان استمرار وصول تقييمات جديدة بأقل جهد.$ar$,
  seo_keywords = $kw$Google review table stand, NFC acrylic review stand Saudi Arabia, in-store review stand, restaurant review stand NFC, counter review display, passive review collection stand, ستاند طاولة تقييم جوجل, حامل أكريليك NFC للمحلات, ستاند تقييمات للمطاعم$kw$,
  features_en = '["Premium acrylic desk/counter design","Passive, always-on review collection","Tap or QR code to Google reviews","Blends naturally into store decor","No staff prompting required","Ideal for restaurants, clinics & retail"]',
  features_ar = '["تصميم أكريليك فاخر للطاولة أو الكاشير","جمع تقييمات مستمر وتلقائي","فتح تقييم جوجل باللمس أو QR","يندمج بأناقة مع ديكور المتجر","دون الحاجة لطلب الموظفين","مثالي للمطاعم والعيادات والمحلات"]'
where slug = 'premium-table-stand';

-- ── Quick Share Table Stand ───────────────────────────────────────────
update public.products set
  description = $en$One stand, endless possibilities — Rawajcard's quick-share table stand lets you decide exactly what customers see with a single tap: your digital menu, website, social media profiles, Google review page, or a custom order form. Set the link once through your Rawajcard dashboard, and every tap on the stand opens that destination instantly on the customer's phone, with a QR code available as backup. Because it's fully customizable, the same stand can serve a restaurant's menu today and a retail shop's Instagram tomorrow — and you can change what it links to any time your needs change, without buying new hardware or reprinting anything. It's a practical upgrade for restaurants and cafés looking to replace static paper menus or plain QR-code table cards with something faster, more professional, and reusable across campaigns. Place it on tables, counters, or a host stand, and let customers self-serve the exact information you want them to have, exactly when they want it — no app, no waiting for staff, no printed materials to run out of.$en$,
  description_ar = $ar$ستاند واحد وإمكانيات لا حدود لها — ستاند رواج كارد للمشاركة السريعة يتيح لك تحديد ما يراه عملاؤك بالضبط بلمسة واحدة: منيو رقمي، موقعك الإلكتروني، حساباتك على وسائل التواصل، صفحة تقييم جوجل، أو نموذج طلب مخصص. حدد الرابط مرة واحدة من لوحة تحكم رواج كارد، وكل لمسة على الستاند تفتح تلك الوجهة فوراً على هاتف العميل، مع رمز QR كبديل جاهز. ولأنه قابل للتخصيص الكامل، يمكن لنفس الستاند أن يعرض منيو مطعم اليوم وحساب إنستقرام لمحل تجاري غداً — ويمكنك تغيير وجهة الرابط في أي وقت تتغير فيه احتياجاتك، دون شراء جهاز جديد أو إعادة طباعة أي شيء. إنه ترقية عملية للمطاعم والمقاهي التي تريد استبدال قوائم الطعام الورقية الثابتة أو بطاقات QR البسيطة على الطاولات بتجربة أسرع وأكثر احترافية وقابلة لإعادة الاستخدام مع كل حملة جديدة. ضعه على الطاولات أو الكاشير أو طاولة الاستقبال، ودع عملاءك يصلون بأنفسهم إلى المعلومة التي تريدها بالضبط، في اللحظة التي يحتاجونها — دون تطبيق، ودون انتظار الموظفين، ودون مواد مطبوعة تنتهي كمياتها.$ar$,
  seo_keywords = $kw$NFC table stand, multi-purpose NFC stand Saudi Arabia, restaurant menu NFC stand, customizable NFC link stand, digital menu tap stand, reusable NFC display stand, ستاند طاولة NFC متعدد الاستخدامات, ستاند منيو رقمي للمطاعم, ستاند مشاركة سريعة بالسعودية$kw$,
  features_en = '["Fully customizable tap destination","Change the link anytime, no new hardware","Tap or QR code access","Great for menus, socials & reviews","Reusable across campaigns & seasons","Acrylic stand fits any counter or table"]',
  features_ar = '["وجهة اللمس قابلة للتخصيص بالكامل","غيّر الرابط في أي وقت دون جهاز جديد","وصول باللمس أو QR","مثالي للمنيو والسوشيال والتقييمات","قابل لإعادة الاستخدام مع كل حملة","ستاند أكريليك يناسب أي طاولة أو كاشير"]'
where slug = 'quick-share-stand';
